version: "3.8"

services:
  postgredb:
    container_name: postgredb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      PGDATA: /data/postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5430:5432
    expose:
      - 5430
  app:
    depends_on:
      - postgredb
    build: ./FileManagement
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - 6868:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://localhost:5432/postgres",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "admin123",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "create-drop"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
